---
title: "Basics of Medicare Advantage"
author: "Ian McCarthy | Emory University"
format: 
  revealjs:
    theme: [moon]
    preview-links: auto
    chalkboard:
      boardmarker-width: 5
    slide-number: true
    width: 1600
    height: 900    
#    embed-resources: true
from: markdown+emoji
execute: 
  echo: true
---

```{r}
#| include: false
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, lubridate, gapminder, scales,
               hrbrthemes, gganimate, OECD, here)
```


## What is Medicare Advantage

- Private provision of health insurance for Medicare beneficiaries
- Medicare "replacement" plans

::: {.fragment}
- It's just private insurance for those eligible for Medicare
:::

---

## Medicare Advantage History

- Existed since 1980s, formalized in the 1990s, expanded in 2000s
- Medicare+Choice as part of Balanced Budget Act in 1997
- Largest expansion: Medicare Modernization Act in 2003 (also brought Medicare Part D)

---

## Medicare Advantage Details

In its current form...

- Insurers submit plan details and a price needed to cover traditional Medicare ("bid")
- If approved, Medicare pays risk-adjusted bid *or* benchmark
- Bid $<$ benchmark, insurer gets a rebate
- Bid $>$ benchmark, insurer charges premium
- Seperate bidding for Part D

---

## Medicare Advantage in Real Life

Let's take a look at the Medicare Advantage plan options...

::: {.fragment}
[Medicare Plan Finder](https://www.medicare.gov/plan-compare/)
:::

---

## Medicare Advantage Quality Ratings

- Initial MA Star Ratings (2007)
- Overall rating introduced in 2009
- Complicated formula...

::: {.fragment}
- **key point:** ratings from several domains are averaged and then rounded
- More details available [here](https://www.cms.gov/Medicare/Prescription-Drug-Coverage/PrescriptionDrugCovGenIn/PerformanceData)
:::

---

## Role of Quality Ratings

- Potentially affect plan choice
- Quality bonus program in 2012
  - Demonstration program at first (2012 through 2015)
  - ACA quality bonus payments begin 2015
  
---

## Details of QBP

Eligible plans may receive two bonuses:

1. Benchmark bonus: Increased benchmark payment of up to 5\%
2. Rebate bonus: Share of bid-benchmark differential going back to insurer (from 50% up to 70%)


::: {.fragment}
- Applied to plans with 3-stars and above from 2012-2015 (demonstration period)
- Applied to plans with 4-stars and above beginning 2015 
:::

---

## Some good primers

- [KFF Bonus Payment Illustration](pics/kff-illustration.pdf)
- [2021 Star Ratings and Bonus Payments](https://www.kff.org/medicare/issue-brief/medicare-advantage-in-2021-star-ratings-and-bonuses/)


# Quality Ratings and Plan Choice


---

## Quality Ratings as Information Disclosure


